# your domain
domain: tro.zqwnan.tk

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://tro.zqwnan.tk/source.yaml